### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by lucy-sees** [MPDADDY/capstone_prize-giving_day#2]
Hi @MPDADDY ,

Your project is looking great!
Congratulations! 🎉

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

###  To Highlights
:heavy_check_mark: Descriptive commit messages 
:heavy_check_mark: Professional looking README file
:heavy_check_mark: Good overall design 
:heavy_check_mark: Good use of GitHub flows 👍 

Cheers and Happy coding!👏👏👏

------

**Comment by MPDADDY** [comment]
Issue closed
